In [38]:
import numpy as np
import cv2
n = 0;
image = cv2.imread("c1_23.jpg")
gray = cv2.cvtColor(image,cv2.COLOR_BGR2GRAY) # grayscale
_,thresh = cv2.threshold(gray,200,255,cv2.THRESH_BINARY_INV) 
#threshold
kernel = cv2.getStructuringElement(cv2.MORPH_CROSS,(3,3))
dilated = cv2.dilate(thresh,kernel,iterations = 4) # dilate
image2,contours, hierarchy =cv2.findContours(dilated,cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_NONE) 
# get contours
# for each contour found, draw a rectangle around it on original 
image
i = [];
for contour in contours:
     
    # get rectangle bounding contour
   
    [x,y,w,h] = cv2.boundingRect(contour)
    a =  [x,y,w,h]
  
    # discard areas that are too large
 
    if h>300 and w>300:
 
        continue
    # discard areas that are too small
 
    if h<40 or w<40:
 
        continue
    # draw rectangle around contour on original image

    newrect = cv2.rectangle(image,(x,y),(x+w,y+h),(255,0,255),2)
    i.append(a)

# write original image with added contours to disk  
cv2.imwrite("contoured.jpg", image)
cv2.imwrite("test.jpg", dilated)
print(i)


[[21, 70, 121, 66], [68, 49, 52, 50], [8, 3, 136, 119]]


a = i[1][0]
b = i[1][1]
c = i[1][2]
d = i[1][3]
q = i[0][0]
w = i[0][1]
e = i[0][2]
r = i[0][3]

In [ ]:
crop_img2 = image[w:w+r, q:q+e]
cv2.imwrite("contoured4.jpg", crop_img2)
crop_img = image[b:b+d, a:a+c]
cv2.imwrite("contoured3.jpg", crop_img)

In [6]:
components = []
n = 0
for x in i:
    print(x)
    a = x[0]
    b = x[1]
    c = x[2]
    d = x[3]
    crop_img2 = image[b:b+d, a:a+c]
    components.append(crop_img2)
    n+=1
    filename = "thefile_%d.jpg"%n
    cv2.imwrite(filename, crop_img2)
    cv2.imshow('image%d'%n,crop_img2)

In [2]:
import numpy as np
import cv2
from matplotlib import pyplot as plt

img = cv2.imread('c1_1.jpg')
gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
ret, thresh = cv2.threshold(gray,0,255,cv2.THRESH_BINARY_INV+cv2.THRESH_OTSU)

In [3]:
cv2.imwrite("contoured.jpg", thresh)

image2,contours, hierarchy =cv2.findContours(thresh,cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_NONE) 
i = [];
[x,y,w,h] = cv2.boundingRect(contours)
a =  [x,y,w,h]
newrect = cv2.rectangle(image,(x,y),(x+w,y+h),(255,0,255),2)
i.append(a)
cv2.imwrite("contoured.jpg", image)

TypeError: array is not a numpy array, neither a scalar

In [4]:
# noise removal
kernel = np.ones((3,3),np.uint8)

# sure background area
sure_bg = cv2.dilate(thresh,kernel,iterations=1)

# Finding sure foreground area
dist_transform = cv2.distanceTransform(opening,cv2.DIST_L2,5)
ret, sure_fg = cv2.threshold(dist_transform,0.7*dist_transform.max(),255,0)

# Finding unknown region
sure_fg = np.uint8(sure_fg)
unknown = cv2.subtract(sure_bg,sure_fg)

NameError: name 'opening' is not defined

In [41]:
cv2.imwrite("opening.jpg", )

True

In [22]:
# Marker labelling
ret, markers = cv2.connectedComponents(thresh)

# Add one to all labels so that sure background is not 0, but 1
markers = markers+1

# Now, mark the region of unknown with zero
markers[unknown==255] = 0

In [23]:
markers = cv2.watershed(img,markers)
img[markers == -1] = [255,0,0]

In [24]:
cv2.imwrite("contoured.jpg", markers)

True

In [12]:
# Import the cv2 library
import cv2
# Read the image you want connected components of
img = cv2.imread('circuit2.jpg')
img = cv2.resize(img,(255,255))
gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
ret, thresh = cv2.threshold(gray,0,255,cv2.THRESH_BINARY_INV+cv2.THRESH_OTSU)
kernel = cv2.getStructuringElement(cv2.MORPH_CROSS,(3,3))
erosion = cv2.erode(thresh,kernel,iterations = 1)
dilated = cv2.dilate(thresh,kernel,iterations = 1) # dilate
# You need to choose 4 or 8 for connectivity type
cv2.imwrite("dilated.jpg", dilated)
cv2.imwrite("threshhold.jpg", thresh)

connectivity = 8  
# Perform the operation
output = cv2.connectedComponentsWithStats(dilated, connectivity, cv2.CV_32S)
# Get the results
# The first cell is the number of labels
num_labels = output[0]
# The second cell is the label matrix
labels = output[1]
# The third cell is the stat matrix
stats = output[2]
# The fourth cell is the centroid matrix
centroids = output[3]
ret2, labels2 = cv2.connectedComponents(dilated)
print(stats)

[[    0     0   255   255 59507]
 [   54    37   182    75  1821]
 [   44    50   185   179  3344]
 [  204   120    20     7   114]
 [  197   132    39     8   239]]


In [13]:
def imshow_components(labels):
    # Map component labels to hue val
    label_hue = np.uint8(179*labels/np.max(labels))
    blank_ch = 255*np.ones_like(label_hue)
    labeled_img1 = cv2.merge([label_hue, blank_ch, blank_ch])

    # cvt to BGR for display
    labeled_img = cv2.cvtColor(labeled_img1, cv2.COLOR_HSV2BGR)

    # set bg label to black
    labeled_img[label_hue==0] = 0

    cv2.imwrite('labeled.png', labeled_img)
    cv2.waitKey()

In [14]:
imshow_components(labels)

In [2]:
threshold_area = 100
readname = "c1_1.JPG"
image = cv2.imread(readname)
image = cv2.resize(image,(255,255))
i = [];
ret, labels = cv2.connectedComponents(thresh)
for label in range(1,ret):
    mask = np.array(labels, dtype=np.uint8)
    mask[labels == label] = 255
    n+=1
    filename = "thefile_%d.jpg"%n
    cv2.imwrite(filename,mask)
    img = cv2.imread(filename)
    gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY) # convert to grayscale
    im2, contours, hierarchy = cv2.findContours(gray,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)

    image
    i = [];
    for contour in contours:
     
    # get rectangle bounding contour
   
        [x,y,w,h] = cv2.boundingRect(contour)
        a =  [x,y,w,h]
        
    # discard areas that are too small
   
 
    

        newrect = cv2.rectangle(image,(x,y),(x+w,y+h),(255,0,255),2) #find coordinates
        i.append(a) #stores coordinates in array
print(i)
cv2.imwrite("contoured2.jpg", newrect)




[[89, 151, 1, 1], [76, 151, 1, 1], [85, 149, 7, 3], [73, 149, 2, 3], [92, 147, 4, 5], [56, 143, 2, 2], [95, 137, 1, 1], [48, 134, 2, 3], [85, 130, 2, 2], [55, 129, 2, 1], [94, 125, 1, 1], [48, 125, 48, 27], [80, 149, 3, 3], [67, 149, 3, 3], [62, 149, 3, 3], [79, 148, 3, 3], [77, 148, 3, 3], [66, 148, 3, 3], [78, 147, 3, 3], [67, 147, 3, 3], [76, 146, 3, 3], [58, 146, 6, 4], [84, 145, 3, 3], [74, 145, 4, 4], [62, 145, 5, 3], [60, 144, 3, 3], [88, 143, 4, 4], [76, 143, 4, 5], [59, 143, 3, 3], [80, 142, 3, 3], [75, 142, 4, 4], [63, 141, 3, 3], [85, 140, 4, 4], [73, 140, 3, 4], [65, 140, 4, 4], [62, 140, 3, 3], [75, 139, 4, 4], [64, 139, 3, 3], [76, 138, 3, 3], [72, 138, 4, 3], [61, 138, 13, 9], [56, 138, 3, 4], [49, 138, 5, 6], [52, 137, 3, 3], [80, 136, 7, 11], [82, 135, 3, 3], [76, 135, 3, 3], [74, 135, 4, 5], [72, 135, 3, 4], [75, 134, 3, 3], [73, 134, 3, 3], [85, 133, 3, 3], [83, 133, 3, 3], [77, 133, 7, 12], [74, 133, 3, 3], [53, 133, 6, 7], [75, 132, 4, 3], [65, 132, 6, 9], [57, 132

True

In [7]:
# import os
components = []
readname = "c1_11.JPG"
image = cv2.imread(readname)
n = 0
for x in i:
    print(x)
    a = x[0]
    b = x[1]
    c = x[2]
    d = x[3]
    crop_img2 = image[b:b+d, a:a+c]
    components.append(crop_img2)
    n+=1
    filename = "thefile_%d.jpg"%n
    path =r'C:\Users\mitchellel\test\Test Images'
    cv2.imwrite(os.path.join(path , filename), crop_img2)

In [47]:
# Standard imports
import cv2
import numpy as np;
 
# Read image
im = cv2.imread("circuit2.jpg")
 
gray = cv2.cvtColor(im,cv2.COLOR_BGR2GRAY) # grayscale
_,thresh = cv2.threshold(gray,200,255,cv2.THRESH_BINARY_INV) 
#threshold
kernel = cv2.getStructuringElement(cv2.MORPH_CROSS,(3,3))
dilated = cv2.dilate(thresh,kernel,iterations = 3) # dilate
image2,contours, hierarchy =cv2.findContours(dilated,cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_NONE)    

# Setup SimpleBlobDetector parameters.
params = cv2.SimpleBlobDetector_Params()
 
# Change thresholds
params.minThreshold = 10;
params.maxThreshold = 200;
 
# Filter by Area.
params.filterByArea = True
params.minArea = 500
 
# Filter by Circularity
params.filterByCircularity = True
params.minCircularity = 0.5
 
# Filter by Convexity
params.filterByConvexity = False
params.minConvexity = 0.87
 
# Filter by Inertia
params.filterByInertia = True
params.minInertiaRatio = 0.50
 
# Create a detector with the parameters
ver = (cv2.__version__).split('.')
if int(ver[0]) < 3 :
    detector = cv2.SimpleBlobDetector(params)
else : 
    detector = cv2.SimpleBlobDetector_create(params)
    
    # Detect blobs.
keypoints = detector.detect(dilated)
 
# Draw detected blobs as red circles.
# cv2.DRAW_MATCHES_FLAGS_DRAW_RICH_KEYPOINTS ensures the size of the circle corresponds to the size of blob
im_with_keypoints = cv2.drawKeypoints(dilated, keypoints, np.array([]), (0,0,255), cv2.DRAW_MATCHES_FLAGS_DRAW_RICH_KEYPOINTS)
 
    
# Show keypoints
cv2.imwrite("ctest2.jpg", im_with_keypoints)
cv2.waitKey(0)

-1

In [6]:
import cv2
import numpy as np

img = cv2.imread('circuit2.jpg',0)
img = cv2.medianBlur(img,5)
cimg = cv2.cvtColor(img,cv2.COLOR_GRAY2BGR)
edges = cv2.Canny(img,100,200)

circles = cv2.HoughCircles(edges,cv2.HOUGH_GRADIENT,1,10,
                            param1=50,param2=30)

circles = np.uint16(np.around(circles))
for i in circles[0,:]:
    # draw the outer circle
    cv2.circle(cimg,(i[0],i[1]),i[2],(0,255,0),2)
    # draw the center of the circle
    cv2.circle(cimg,(i[0],i[1]),2,(0,0,255),3)

cv2.imwrite('detected.jpg',cimg)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [29]:
import numpy as np
import cv2 as cv
face_cascade = cv.CascadeClassifier('cascade.xml')

img = cv.imread('circuit1_2_24.jpg')
gray = cv.cvtColor(img, cv.COLOR_BGR2GRAY)

In [30]:
dots = face_cascade.detectMultiScale(gray, 1.1, 3)
for (x,y,w,h) in dots:
    cv.rectangle(img,(x,y),(x+w,y+h),(255,255,255),-1)
    roi_gray = gray[y:y+h, x:x+w]
    roi_color = img[y:y+h, x:x+w]

cv.imwrite('testdot.jpg',img)

True